In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [7]:
df = pd.read_csv("/home/aasif057/Downloads/MLA1_DATA/CSV/MindBigData_Imagenet_Insight_n10565667_993_1_1173.csv")

In [8]:
df

,AF3,4274.35897435897,4294.8717948718,4276.92307692308,4274.35897435897.1,4297.4358974359,4292.30769230769,4286.66666666667,4306.15384615385,4296.41025641026,...,4299.48717948718.3,4272.82051282051.3,4271.28205128205.1,4285.12820512821.1,4291.79487179487,4283.07692307692.2,4269.74358974359.3,4276.92307692308.3,4293.33333333333.4,4291.28205128205.1
0,AF4,4191.282051,4187.692308,4210.256410,4227.692308,4224.615385,4213.846154,4204.615385,4198.461538,4216.410256,...,4204.615385,4213.846154,4197.435897,4182.051282,4206.666667,4228.205128,4210.256410,4195.384615,4199.487179,4201.025641
1,T7,4236.923077,4256.410256,4240.512821,4218.974359,4228.205128,4233.846154,4224.102564,4228.205128,4231.794872,...,4199.487179,4173.846154,4168.205128,4191.794872,4218.461538,4205.128205,4178.461538,4178.461538,4191.794872,4194.871795
2,T8,4351.794872,4350.256410,4318.461538,4305.641026,4319.487179,4335.897436,4346.666667,4331.794872,4313.846154,...,4301.538462,4336.410256,4360.512821,4339.487179,4335.384615,4344.615385,4341.538462,4334.358974,4322.564103,4312.820513
3,Pz,4189.743590,4172.307692,4146.666667,4140.512821,4157.435897,4185.641026,4198.974359,4180.512821,4157.435897,...,4110.256410,4094.358974,4111.794872,4134.358974,4131.282051,4106.153846,4101.538462,4128.717949,4126.666667,4095.897436